### ISSUE TITLE
Driver do LoRa (SPI)

### ISSUE THREAD

**Issue by bykowskiolaf** [BuzzVerse/lora_esp32_firmware#1]
Driver LoRa - ESP32, komunikacja po SPI

API:
- Status modułu
- Ustawienie parametrów (tx power, spreading factor, error correction, etc).
- Wysyłanie ramki
- Odbieranie ramki

DoD:
- przetestowane na dwóch urządzeniach w trybie nadajnik i odbiornik

**Comment by pkamoda-shani** [comment]
Podepnijcie tutaj proszę branch na którym pracujecie.
